name: Bug
title: '[Bug] '
description: Bug反馈
labels: [ 'bug' ]

body:
  - type: checkboxes
    attributes:
      label: 注意事项
      options:
        - label: 提ISSUE前，请确认你已经在GitHub Issues和Discussions里搜索过类似的问题，并且没找到想要的答案。
          required: true
        - label: GitHub Actions问题请到置顶的Issue反馈。
          required: true

  - type: dropdown
    attributes:
      label: 发生Bug时，你的使用方式？
      multiple: false
      options:
        - Python代码
        - jmcomic命令行
    validations:
      required: true

  - type: dropdown
    attributes:
      label: 你是否在禁漫官方网页或APP，验证过相应的功能是正常的？
      multiple: false
      options:
        - 测试过，禁漫官方功能正常
        - 我要反馈的bug无需验证/不方便验证
    validations:
      required: true

  - type: textarea
    attributes:
      label: option配置+源码/命令
      placeholder: 贴一下你的option配置 + 你使用的python代码或命令，这会帮助开发者解决bug。

  - type: textarea
    attributes:
      label: 你预期的结果，与实际结果的差别
      placeholder: |
        1. 预期结果...
        2. 差别...

  - type: textarea
    attributes:
      label: 其他信息
      placeholder: 如果有其他需要补充的信息，可以在这里留言

